export const products = [
  {
    id: "vital-hoodie-noir",
    name: "Vital Monogram Hoodie",
    price: 189,
    compareAt: 240,
    image: "/assets/product-hoodie.jpg",
    images: ["/assets/product-hoodie.jpg", "/assets/product-hoodie.jpg"],
    category: "Hoodies",
    collection: "Core",
    official: true,
    isNew: true,
    colors: ["#0F0F0F", "#FAFAF8", "#3B342E"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.9,
    reviews: 284,
    description:
      "Heavyweight 480gsm brushed fleece with a gold-embroidered SL monogram. Cut oversized for a modern silhouette. Made in Portugal.",
  },
  {
    id: "legacy-tee",
    name: "Legacy Essential Tee",
    price: 72,
    image: "/assets/product-tshirt.jpg",
    images: ["/assets/product-tshirt.jpg", "/assets/product-tshirt.jpg"],
    category: "T-Shirts",
    collection: "Core",
    official: true,
    colors: ["#0F0F0F", "#FAFAF8"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.8,
    reviews: 512,
    description:
      "Premium Peruvian pima cotton, tubular knit. A quiet foundation piece.",
  },
  {
    id: "sovereign-bomber",
    name: "Sovereign Bomber",
    price: 420,
    image: "/assets/product-jacket.jpg",
    images: ["/assets/product-jacket.jpg", "/assets/product-jacket.jpg"],
    category: "Jackets",
    collection: "Signature",
    official: true,
    isNew: true,
    colors: ["#0F0F0F"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
    reviews: 96,
    description: "Water-resistant technical shell with 18k gold-tone hardware.",
  },
  {
    id: "monogram-cap",
    name: "Monogram Cap",
    price: 68,
    image: "/assets/product-cap.jpg",
    images: ["/assets/product-cap.jpg", "/assets/product-cap.jpg"],
    category: "Accessories",
    collection: "Core",
    official: true,
    colors: ["#0F0F0F", "#3B342E"],
    sizes: ["One Size"],
    rating: 4.9,
    reviews: 178,
    description: "Structured six-panel cap with gold thread SL monogram.",
  },
  {
    id: "atelier-coat",
    name: "Atelier Camel Coat",
    price: 890,
    compareAt: 1200,
    image: "/assets/category-women.jpg",
    images: ["/assets/category-women.jpg", "/assets/category-women.jpg"],
    category: "Outerwear",
    collection: "Signature",
    official: true,
    colors: ["#C9A788", "#0F0F0F"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.9,
    reviews: 44,
    description: "Double-face virgin wool overcoat, hand-finished.",
  },
  {
    id: "obsidian-suit",
    name: "Obsidian Tailored Coat",
    price: 1240,
    image: "/assets/category-men.jpg",
    images: ["/assets/category-men.jpg", "/assets/category-men.jpg"],
    category: "Outerwear",
    collection: "Signature",
    official: true,
    colors: ["#0F0F0F"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.8,
    reviews: 61,
    description: "Half-canvas construction with a sculpted shoulder.",
  },
  {
    id: "onyx-accessories",
    name: "Onyx & Gold Set",
    price: 340,
    image: "/assets/category-accessories.jpg",
    images: ["/assets/category-accessories.jpg", "/assets/category-accessories.jpg"],
    category: "Accessories",
    collection: "Limited",
    official: true,
    isNew: true,
    colors: ["#0F0F0F"],
    sizes: ["One Size"],
    rating: 4.7,
    reviews: 22,
    description: "Curated set: leather wallet, cuban chain, acetate frames.",
  },
  {
    id: "sl-tee-white",
    name: "SL Signature Tee",
    price: 85,
    image: "/assets/product-tshirt.jpg",
    images: ["/assets/product-tshirt.jpg", "/assets/product-tshirt.jpg"],
    category: "T-Shirts",
    collection: "Core",
    official: true,
    colors: ["#FAFAF8", "#0F0F0F"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.9,
    reviews: 203,
    description: "Signature SL screenprint on heavyweight cotton.",
  },
];

export const categories = [
  { name: "All", href: "/shop" },
  { name: "New Arrivals", href: "/shop?sort=newest" },
  { name: "T-Shirts", href: "/shop?category=T-Shirts" },
  { name: "Hoodies", href: "/shop?category=Hoodies" },
  { name: "Jackets", href: "/shop?category=Jackets" },
  { name: "Outerwear", href: "/shop?category=Outerwear" },
  { name: "Accessories", href: "/shop?category=Accessories" },
];

export const categoryImages = [
  { name: "Men", image: "/assets/category-men.jpg", href: "/shop?category=Men" },
  { name: "Women", image: "/assets/category-women.jpg", href: "/shop?category=Women" },
  { name: "Hoodies", image: "/assets/product-hoodie.jpg", href: "/shop?category=Hoodies" },
  { name: "Jackets", image: "/assets/product-jacket.jpg", href: "/shop?category=Jackets" },
  { name: "Accessories", image: "/assets/category-accessories.jpg", href: "/shop?category=Accessories" },
];

export const collections = [
  {
    id: "core",
    name: "Core Collection",
    description: "Essential pieces, built to last.",
    image: "/assets/product-hoodie.jpg",
    slug: "core",
  },
  {
    id: "signature",
    name: "Signature Collection",
    description: "Statement pieces for the confident.",
    image: "/assets/product-jacket.jpg",
    slug: "signature",
  },
  {
    id: "limited",
    name: "Limited Edition",
    description: "Small batches. Rare finds.",
    image: "/assets/category-accessories.jpg",
    slug: "limited",
  },
];

export const reviews = [
  {
    quote:
      "Every detail whispers quality. The Vital Hoodie feels like a piece I'll wear for a decade.",
    author: "Amara O.",
    location: "London",
  },
  {
    quote:
      "Saint Vital redefines what modern fashion should feel like. Effortless, impeccable.",
    author: "Kenji T.",
    location: "Tokyo",
  },
  {
    quote:
      "The quality is unmatched. My go-to for timeless pieces that actually last.",
    author: "Elena V.",
    location: "Milan",
  },
  {
    quote:
      "Finally a brand that cares about fit, fabric, and finish. Worth every penny.",
    author: "Marcus J.",
    location: "New York",
  },
];

export const findProduct = (id) => products.find((p) => p.id === id);
export const findCollection = (slug) => collections.find((c) => c.slug === slug);
